{{- if and .Values.admin.token (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachic.fullname" . }}
  labels:
    {{- include "cachic.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.admin.existingSecretKey }}: {{ .Values.admin.token | quote }}
{{- end }}
